#!/bin/bash
chmod 777 cache/backend
chmod 777 cache/frontend
chmod 777 images/logo
chmod 777 images/notice_images
chmod 777 images/notice_images/thumbs
chmod 777 media/albums
chmod 777 media/categories/album
chmod 777 media/categories/game
chmod 777 media/categories/video
chmod 777 media/csv
chmod 777 media/games/swf
chmod 777 media/games/tmb
chmod 777 media/games/tmb/orig
chmod 777 media/photos
chmod 777 media/photos/tmb
chmod 777 media/player/logo
chmod 777 media/users
chmod 777 media/users/orig
chmod 777 media/videos/tmb
chmod 777 media/videos/vid
chmod 777 media/videos/h264
chmod 777 templates/emails
chmod 777 tmp/albums
chmod 777 tmp/avatars
chmod 777 tmp/downloads
chmod 777 tmp/logs
chmod 777 tmp/sessions
chmod 777 tmp/thumbs
chmod 777 tmp/uploader
chmod 777 aembed.sh
chmod 777 include/config.local.php
chmod 777 scripts/media_general.txt
chmod 777 scripts/media_video.txt
chmod 777 templates/backend/default/analytics/analytics.tpl
chmod 777 templates/emails/blog_comment.tpl
chmod 777 templates/emails/friend_request.tpl
chmod 777 templates/emails/game_approve.tpl
chmod 777 templates/emails/game_comment.tpl
chmod 777 templates/emails/game_upload.tpl
chmod 777 templates/emails/invite.tpl
chmod 777 templates/emails/photo_approve.tpl
chmod 777 templates/emails/photo_comment.tpl
chmod 777 templates/emails/photo_upload.tpl
chmod 777 templates/emails/player_email.tpl
chmod 777 templates/emails/recover_password.tpl
chmod 777 templates/emails/request_approved.tpl
chmod 777 templates/emails/request_rejected.tpl
chmod 777 templates/emails/share_game.tpl
chmod 777 templates/emails/share_photo.tpl
chmod 777 templates/emails/share_video.tpl
chmod 777 templates/emails/subscribe_email.tpl
chmod 777 templates/emails/verify_email.tpl
chmod 777 templates/emails/video_approve.tpl
chmod 777 templates/emails/video_comment.tpl
chmod 777 templates/emails/video_upload.tpl
chmod 777 templates/emails/wall_comment.tpl
chmod 777 templates/emails/welcome.tpl
chmod 777 templates/frontend/bright-blue/static/2257.tpl
chmod 777 templates/frontend/bright-blue/static/advertise.tpl
chmod 777 templates/frontend/bright-blue/static/dmca.tpl
chmod 777 templates/frontend/bright-blue/static/faq.tpl
chmod 777 templates/frontend/bright-blue/static/privacy.tpl
chmod 777 templates/frontend/bright-blue/static/terms.tpl
chmod 777 templates/frontend/bright-blue/static/webmasters.tpl
chmod 777 templates/frontend/bright-blue/static/whatis.tpl
chmod 777 templates/frontend/bright-corai/static/2257.tpl
chmod 777 templates/frontend/bright-corai/static/advertise.tpl
chmod 777 templates/frontend/bright-corai/static/dmca.tpl
chmod 777 templates/frontend/bright-corai/static/faq.tpl
chmod 777 templates/frontend/bright-corai/static/privacy.tpl
chmod 777 templates/frontend/bright-corai/static/terms.tpl
chmod 777 templates/frontend/bright-corai/static/webmasters.tpl
chmod 777 templates/frontend/bright-corai/static/whatis.tpl
chmod 777 templates/frontend/bright-corai-alternate/static/2257.tpl
chmod 777 templates/frontend/bright-corai-alternate/static/advertise.tpl
chmod 777 templates/frontend/bright-corai-alternate/static/dmca.tpl
chmod 777 templates/frontend/bright-corai-alternate/static/faq.tpl
chmod 777 templates/frontend/bright-corai-alternate/static/privacy.tpl
chmod 777 templates/frontend/bright-corai-alternate/static/terms.tpl
chmod 777 templates/frontend/bright-corai-alternate/static/webmasters.tpl
chmod 777 templates/frontend/bright-corai-alternate/static/whatis.tpl
chmod 777 templates/frontend/bright-green/static/2257.tpl
chmod 777 templates/frontend/bright-green/static/advertise.tpl
chmod 777 templates/frontend/bright-green/static/dmca.tpl
chmod 777 templates/frontend/bright-green/static/faq.tpl
chmod 777 templates/frontend/bright-green/static/privacy.tpl
chmod 777 templates/frontend/bright-green/static/terms.tpl
chmod 777 templates/frontend/bright-green/static/webmasters.tpl
chmod 777 templates/frontend/bright-green/static/whatis.tpl
chmod 777 templates/frontend/bright-magenta/static/2257.tpl
chmod 777 templates/frontend/bright-magenta/static/advertise.tpl
chmod 777 templates/frontend/bright-magenta/static/dmca.tpl
chmod 777 templates/frontend/bright-magenta/static/faq.tpl
chmod 777 templates/frontend/bright-magenta/static/privacy.tpl
chmod 777 templates/frontend/bright-magenta/static/terms.tpl
chmod 777 templates/frontend/bright-magenta/static/webmasters.tpl
chmod 777 templates/frontend/bright-magenta/static/whatis.tpl
chmod 777 templates/frontend/bright-mint/static/2257.tpl
chmod 777 templates/frontend/bright-mint/static/advertise.tpl
chmod 777 templates/frontend/bright-mint/static/dmca.tpl
chmod 777 templates/frontend/bright-mint/static/faq.tpl
chmod 777 templates/frontend/bright-mint/static/privacy.tpl
chmod 777 templates/frontend/bright-mint/static/terms.tpl
chmod 777 templates/frontend/bright-mint/static/webmasters.tpl
chmod 777 templates/frontend/bright-mint/static/whatis.tpl
chmod 777 templates/frontend/bright-orange/static/2257.tpl
chmod 777 templates/frontend/bright-orange/static/advertise.tpl
chmod 777 templates/frontend/bright-orange/static/dmca.tpl
chmod 777 templates/frontend/bright-orange/static/faq.tpl
chmod 777 templates/frontend/bright-orange/static/privacy.tpl
chmod 777 templates/frontend/bright-orange/static/terms.tpl
chmod 777 templates/frontend/bright-orange/static/webmasters.tpl
chmod 777 templates/frontend/bright-orange/static/whatis.tpl
chmod 777 templates/frontend/bright-purple/static/2257.tpl
chmod 777 templates/frontend/bright-purple/static/advertise.tpl
chmod 777 templates/frontend/bright-purple/static/dmca.tpl
chmod 777 templates/frontend/bright-purple/static/faq.tpl
chmod 777 templates/frontend/bright-purple/static/privacy.tpl
chmod 777 templates/frontend/bright-purple/static/terms.tpl
chmod 777 templates/frontend/bright-purple/static/webmasters.tpl
chmod 777 templates/frontend/bright-purple/static/whatis.tpl
chmod 777 templates/frontend/dark-blue/static/2257.tpl
chmod 777 templates/frontend/dark-blue/static/advertise.tpl
chmod 777 templates/frontend/dark-blue/static/dmca.tpl
chmod 777 templates/frontend/dark-blue/static/faq.tpl
chmod 777 templates/frontend/dark-blue/static/privacy.tpl
chmod 777 templates/frontend/dark-blue/static/terms.tpl
chmod 777 templates/frontend/dark-blue/static/webmasters.tpl
chmod 777 templates/frontend/dark-blue/static/whatis.tpl
chmod 777 templates/frontend/dark-corai/static/2257.tpl
chmod 777 templates/frontend/dark-corai/static/advertise.tpl
chmod 777 templates/frontend/dark-corai/static/dmca.tpl
chmod 777 templates/frontend/dark-corai/static/faq.tpl
chmod 777 templates/frontend/dark-corai/static/privacy.tpl
chmod 777 templates/frontend/dark-corai/static/terms.tpl
chmod 777 templates/frontend/dark-corai/static/webmasters.tpl
chmod 777 templates/frontend/dark-corai/static/whatis.tpl
chmod 777 templates/frontend/dark-green/static/2257.tpl
chmod 777 templates/frontend/dark-green/static/advertise.tpl
chmod 777 templates/frontend/dark-green/static/dmca.tpl
chmod 777 templates/frontend/dark-green/static/faq.tpl
chmod 777 templates/frontend/dark-green/static/privacy.tpl
chmod 777 templates/frontend/dark-green/static/terms.tpl
chmod 777 templates/frontend/dark-green/static/webmasters.tpl
chmod 777 templates/frontend/dark-green/static/whatis.tpl
chmod 777 templates/frontend/dark-magenta/static/2257.tpl
chmod 777 templates/frontend/dark-magenta/static/advertise.tpl
chmod 777 templates/frontend/dark-magenta/static/dmca.tpl
chmod 777 templates/frontend/dark-magenta/static/faq.tpl
chmod 777 templates/frontend/dark-magenta/static/privacy.tpl
chmod 777 templates/frontend/dark-magenta/static/terms.tpl
chmod 777 templates/frontend/dark-magenta/static/webmasters.tpl
chmod 777 templates/frontend/dark-magenta/static/whatis.tpl
chmod 777 templates/frontend/dark-magenta-alternate/static/2257.tpl
chmod 777 templates/frontend/dark-magenta-alternate/static/advertise.tpl
chmod 777 templates/frontend/dark-magenta-alternate/static/dmca.tpl
chmod 777 templates/frontend/dark-magenta-alternate/static/faq.tpl
chmod 777 templates/frontend/dark-magenta-alternate/static/privacy.tpl
chmod 777 templates/frontend/dark-magenta-alternate/static/terms.tpl
chmod 777 templates/frontend/dark-magenta-alternate/static/webmasters.tpl
chmod 777 templates/frontend/dark-magenta-alternate/static/whatis.tpl
chmod 777 templates/frontend/dark-orange/static/2257.tpl
chmod 777 templates/frontend/dark-orange/static/advertise.tpl
chmod 777 templates/frontend/dark-orange/static/dmca.tpl
chmod 777 templates/frontend/dark-orange/static/faq.tpl
chmod 777 templates/frontend/dark-orange/static/privacy.tpl
chmod 777 templates/frontend/dark-orange/static/terms.tpl
chmod 777 templates/frontend/dark-orange/static/webmasters.tpl
chmod 777 templates/frontend/dark-orange/static/whatis.tpl
chmod 777 templates/frontend/dark-red/static/2257.tpl
chmod 777 templates/frontend/dark-red/static/advertise.tpl
chmod 777 templates/frontend/dark-red/static/dmca.tpl
chmod 777 templates/frontend/dark-red/static/faq.tpl
chmod 777 templates/frontend/dark-red/static/privacy.tpl
chmod 777 templates/frontend/dark-red/static/terms.tpl
chmod 777 templates/frontend/dark-red/static/webmasters.tpl
chmod 777 templates/frontend/dark-red/static/whatis.tpl 
